[package]
name = "htmlparser"
version = "0.1.0"
authors = ["Carl Schwan <carlschwan@kde.org>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cxx-build = "1.0.192"

[dependencies]
cxx = "1.0.192"
html2text = "0.16"
